version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    time: "00:00"

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    time: "01:00"

  - package-ecosystem: "gomod"
    directory: "/docs/website"
    target-branch: "main"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    time: "02:00"
